import * as React from 'react';

import CssLogo from "../components/imgs/CssLogo.png";
import HtmlLogo from "../components/imgs/htmlLogo.png";
import ReactLogo from "../components/imgs/ReactLogo.png";
import JsLogo from "../components/imgs/JsLogo.png"
import NodeLogo from "../components/imgs/NodeJs.png"
import DevOpsLogo from "../components/imgs/other_imgs/DevOps.png"
import KubernetesLogo from "../components/imgs/other_imgs/Kubernetes.png"
import JavaLogo from "../components/imgs/other_imgs/Java.png"
import CSharpLogo from "../components/imgs/other_imgs/CSharp.png"
import AWSLogo from "../components/imgs/other_imgs/AWS.png"

import { createTheme } from '@mui/material/styles';
import Typography from '@mui/material/Typography';

import GitHubRepos from './GitHubRepos';

const theme = createTheme({
    palette: {
        primary: {

            main: '#ffffff',

        },
        secondary: {
            light: '#ffffff',
            main: '#ffffff',

            contrastText: '#ffffff',
        },
        contrastThreshold: 3,

        tonalOffset: 0.2,
    },
});

export default function EducationPageText() {
    return (
        <>
            <div className='educationBoxes'>
                {/* React.Js & Js Text */}
                <div className='reactJsBox'>
                    <Typography variant='h6' component="div" gutterBottom sx={{
                        width: 350,
                        height: 200,
                        color: 'white',
                        marginRight: 180,
                        marginTop: 30,
                        display: 'block',
                        float: 'right',
                    }}>
                        I started learning React.Js with Client Side Web Development in my BSc Honours Year to create a Single Page Application that used RESTAPI for an NC500 Route and Hostel list web page. The role of a web browswer, or web client has evolved from simply displaying web pages which are stored on or generated by back-end servers to a platform which can run code that does a major part of the work of the application.

                        <div className='jsLogoPlacement' >
                            <img src={JsLogo} alt={"JsLogo"} width='200' height='200' />
                        </div>
                        <div className='reactLogoPlacement' >
                            <img src={ReactLogo} alt={"ReactLogo"} width='170' height='150' />
                        </div>
                    </Typography>
                </div>
                {/* Node.Js Text */}
                <div className='nodeBox'>
                    <Typography variant='h6' component="div" gutterBottom sx={{
                        width: 300,
                        height: 200,
                        color: 'white',
                        marginRight: 140,
                        marginTop: -26,
                        display: 'block',
                        float: 'right'
                    }}>
                        In my third year of university we were learning Node.Js for our class 'Web Platform Development' which also allowed me and two other class mates to team up for 'Integrated Project' and create a Web Application using Node.Js as a backend for a Netflix inspired game search engine. The Netflix insipred video game search engine was called 'Gameflix' and it would pull an API from steamspy.
                        <div className='nodeLogoPlacement' >
                            <img src={NodeLogo} alt={"NodeLogo"} width='230' height='200' />
                        </div>
                    </Typography>
                </div>
                {/* HTML Text */}
                <div className='htmlBox'>
                    <Typography variant='h6' component="div" gutterBottom sx={{
                        width: 300,
                        height: 200,
                        color: 'white',
                        marginRight: 100,
                        marginTop: -26,
                        display: 'block',
                        float: 'right'
                    }}>
                        Whilst still in my third year at Glasgow Caledonian University, I was tasked to create a Exercise Planner which used Node.Js for the backend but for the Frontend, I had used HTML, CSS and Mustache pages to display it on the browser.
                        <div className='htmlLogoPlacement' >
                            <img src={HtmlLogo} alt={"HtmlLogo"} width='150' height='140' />
                        </div>
                    </Typography>
                </div>
                {/* CSS Logo */}
                <div className='cssLogoPlacement' >
                    <img src={CssLogo} alt={"CssLogo"} width='110' height='140' />
                </div>
                {/* React.Js Text */}
                <div className='ReactBox'>
                    <Typography variant='h6' component="div" gutterBottom sx={{
                        width: 350,
                        height: 200,
                        color: 'white',
                        marginRight: 180,
                        marginTop: 28,
                        display: 'block',
                        float: 'right'
                    }}>
                        On the fourth year of University, I studied the following topics; Client-Side Web Development (React.Js), Secure Software Development, Mobile Platform Development (Java) and UI/UX Design.
                        <br />
                        <br />
                        In the Client-Side Web Development class, I was tasked to create a Single Page Application which used a RESTAPI which I have detailed above to create a hostel list with reviews and able to create itineraries.
                    </Typography>
                </div>
                {/* Java Text */}
                <div className='JavaBox'>
                    <Typography variant='h6' component="div" gutterBottom sx={{
                        width: 400,
                        height: 200,
                        color: 'white',
                        marginRight: 128,
                        marginTop: -26,
                        display: 'block',
                        float: 'right'
                    }}>
                        For the Secure Software Development class, I was learning Brute Force Attacks, Dictionary Attacks, Password Sniffing, Spoofing, Man-In-The-Middle Attacks and SQL Injection Attacks.
                        <br />
                        <br />
                        For the Mobile Platform Development class, I was learning how to create mobile applications for an Android Device using Java. We were tasked to create a Traffic Scotland app which had an array of features, such as; Landscape/Portrait Mode, Google Map Implementation, Pull data from an RSS feed
                    </Typography>
                </div>
                {/* DevOps Logo */}
                <div className='devOpsLogoPlacement' >
                    <img src={DevOpsLogo} alt={'DevOpsLogo'} width='300' height='150' />
                </div>
                {/* Kubernetes Logo */}
                <div className='kubernetesLogoPlacement' >
                    <img src={KubernetesLogo} alt={'KubernetesLogo'}
                        width='150' height='150' />
                </div>
                {/* Java Logo */}
                <div className='JavaLogoPlacement' >
                    <img src={JavaLogo} alt={'JavaLogo'}
                        width='150' height='150' />
                </div>
                {/* C# Logo */}
                <div className='CSharpLogoPlacement' >
                    <img src={CSharpLogo} alt={'CSharpLogo'}
                        width='150' height='150' />
                </div>
                {/* AWS Logo */}
                <div className='AWSLogoPlacement' >
                    <img src={AWSLogo} alt={'AWSLogo'}
                        width='170' height='150' />
                </div>
            </div>
            {/* <div className='GitHubRepos'>
                <GitHubRepos />
            </div> */}
        </>
    )
}